### ISSUE TITLE
Debug-log errors with staggered expiries

### ISSUE THREAD

**Issue by 0xxon** [zeek/broker#129]
Running this zeek script:

```
redef exit_only_after_terminate = T;
global tablestore: opaque of Broker::Store;
event zeek_init()
	{
	tablestore = Broker::create_master("table");
	Broker::put(tablestore, "a", 1, 3sec);
	Broker::put(tablestore, "a", 2, 2sec);
	Broker::put(tablestore, "a", 3, 1sec);
	}
```

Results in a debug log with several errors:
```
[broker/INFO] 2020-06-24T15:38:38.441 PUT a -> 1 with expiry 3000000000ns
[broker/INFO] 2020-06-24T15:38:38.441 PUT a -> 2 with expiry 2000000000ns
[broker/INFO] 2020-06-24T15:38:38.442 PUT a -> 3 with expiry 1000000000ns
[broker/INFO] 2020-06-24T15:38:39.444 EXPIRE a
[broker/INFO] 2020-06-24T15:38:40.444 EXPIRE a
[broker/ERROR] 2020-06-24T15:38:40.444 failed to expire key: error(9, 'broker')
[broker/INFO] 2020-06-24T15:38:41.447 EXPIRE a
[broker/ERROR] 2020-06-24T15:38:41.447 failed to expire key: error(9, 'broker')
```

This is kind of understandable - the element is gone after the first expiry and (to be mean) the earliest expiry is with the last update. It still seems that this should at least be notified differently; it took me a while to figure out that this it what happens.

**Comment by Neverlord** [comment]
The master should ignore the stale expiration messages. I'll take a look.

**Comment by Neverlord** [comment]
The expiration messages only contain the key. When receiving the expiration message, Broker then simply drops a matching entry. This works only as long as there aren't two expiration message "in flight".

I see two ways to fix this:
1. In the ALM branch, data store actors have their own local time management, based on ticks. A tick is 50ms by default at the moment (configurable). So rather than sending delayed messages, the master could instead keep a local timeout table. On each tick, it would check this table for expired keys. Since the master keeps this table, it can make sure that obsolete expiration remainders get removed as necessary. The only downside of using the ticks is that our expiration remainders only get processed as a multiple of the tick duration.
2. In case the first solution is not acceptable because we want expiration remainders to get processed as soon as possible, the second solution is to give a logical timestamp to each entry in the store. The expiration message would then contain key plus this timestamp. When receiving the expiration, the master only drops the entry if the timestamp is still up-to-date. The logical timestamp can be an integer. This would require the master to keep a table with `key -> timestamp` mapping for all entries with expiry.

I'd prefer the first solution, because moving everything to the tick-based time loop reduces complexity (single point of responsibility). Do we need a high resolution for the expirations or is "some time after the expiry" (with up to one tick delay as upper bound) good enough?

**Comment by jsiwek** [comment]
@Neverlord I think hopefully the solution to this is simple (see #134) since we do already store Key+ExpireTime like (2) seems to suggest.  To me, the problem looked like memory backend is just returning a "no-such-key" inappropriately (i.e. that's not an error condition in this case, it's expected).

**Comment by Neverlord** [comment]
Ah, sorry. I should've looked at the actual backend implementation. In this case, your fix should do the trick. 👍
