### ISSUE TITLE
Broker threads usage

### ISSUE THREAD

**Issue by Olerdrive** [zeek/broker#146]
I am trying to examine internals of Broker/CAF in order to eliminate memory leaks in my zeek-python communication and have faced a couple of uncovered by the documentation questions. Probably all of them are naive and mostly refer to CAF, but I would really appreciate if someone could explain them to me.

- First of all I am wondering where published via `Broker::publish` events are stored. My hypothesis is that they are stored in the memory of publisher process (zeek manager process for instance). Is that correct? Assuming my hypothesis is correct,  is there a way to publish them directly to redis or other storage?

- Secondly I find myself totally confused about amount of threads spawned by the initialization of an `Endpoint` instance. Executing the following simple snippet leads to 10 started threads. What they are used for and is there a way to control their amount?

```
import broker
from time import sleep

if __name__ == '__main__':
    ep = broker.Endpoint()
    sleep(60)
```

Thanks in advance!

**Comment by Neverlord** [comment]
> I am trying to examine internals of Broker/CAF in order to eliminate memory leaks in my zeek-python communication and have faced a couple of uncovered by the documentation questions. Probably all of them are naive and mostly refer to CAF

I wouldn't say naive. The Broker docs don't go into much detail on the CAF side of things. Mostly because it would essentially duplicate the CAF docs or add too much details on fringe aspects.

> * First of all I am wondering where published via `Broker::publish` events are stored. My hypothesis is that they are stored in the memory of publisher process (zeek manager process for instance). Is that correct? Assuming my hypothesis is correct,  is there a way to publish them directly to redis or other storage?

Im memory, yes. Internally, Broker uses one CAF actor representing the `broker::endpoint`. This actor has an in-memory queue, called mailbox, that caches incoming (published) data. From there, the actor distributes the data to local subscribers as well as to Broker peers in the network. There's a bit more involved, but that's the gist of it. You cannot publish directly to redis, but you could spin up a local subscriber that pushes to a storage backend of your choice. For that, I'd recommend the asynchronous C++ API in Broker if you need the performance or Python/Zeek as long as you don't want to push *everything* into a storage backend.

> * Secondly I find myself totally confused about amount of threads spawned by the initialization of an `Endpoint` instance. Executing the following simple snippet leads to 10 started threads. What they are used for and is there a way to control their amount?

Starting CAF spins up one thread for logging (CAF-internal logging, this'll mostly sit idle for a default-configured Zeek), one thread for the networking component of CAF that manages connections to Broker peers, a thread pool for scheduling actors (you can configure that via the `Broker::max_threads` parameter in Zeek, by default this is 1 or 2 IIRC), as well as a couple of background threads that run "special" actors that'll mostly sit idle for Broker/Zeek (a CAF config server for example).

So even though Broker spins up a couple of threads, you will usually only see activity from the networking thread as well as from the thread pool (configurable via `Broker::max_threads`).

Hope that answers your questions. 🙂

**Comment by jsiwek** [comment]
Great explanation, thanks.  I'll add a way to configure the thread pool size via Python looks like this:

```python
cfg = broker.Configuration()
cfg.max_threads = 2
ep = broker.Endpoint(cfg)
```
