### ISSUE TITLE
Python Bindings: attach_clone does not block and results in a race condition

### ISSUE THREAD

**Issue by hosom** [zeek/broker#31]
Creating and immediately referencing a clone data store within the Python bindings will result in a `RuntimeError`. This appears to be because the `attach_clone` call returns before the store is ready for use. From my experience, this is a pretty unusual pattern in Python. Is there a way to determine if the store is ready for use before actually referencing it?

Here, we can see this behavior in action:
```
(.env) devel:~/pybroker# cat test-client.py 
import broker

e = broker.Endpoint()
e.peer('127.0.0.1', 47762)

stor = e.attach_clone('bro/discovery/nodes')
print(stor.keys())
(.env) devel:~/pybroker# python test-client.py 
Traceback (most recent call last):
  File "test-client.py", line 7, in <module>
    print(stor.keys())
  File "/root/pybroker/.env/lib/python3.6/site-packages/broker/__init__.py", line 223, in keys
    return Data.to_py(keys.get())
RuntimeError: invalid type found
```

Adding a simple sleep call fixes this:
```
(.env) devel:~/pybroker# cat test-client.py 
import broker
import time

e = broker.Endpoint()
e.peer('127.0.0.1', 47762)

stor = e.attach_clone('bro/discovery/nodes')
time.sleep(3)
print(stor.keys())
(.env) devel:~/pybroker# python test-client.py 
{'control', 'proxy-1', 'worker-1', 'logger', 'manager', 'worker-2'}
```

**Comment by jsiwek** [comment]
The `attach_clone()` method is indeed meant to be asynchronous and making queries against the returned value may fail at any time (due to not being connected yet, or later becoming disconnected).

But the problem here was was specifically with that `keys()` method throwing an exception instead of returning `None` like other query methods are supposed to do in the case of a failed query.  This is now fixed in master or you can essentially workaround by defining your own method that does the same thing as the fix:

```python
e = broker.Endpoint()
e.peer('127.0.0.1', 9999)
s = e.attach_clone('test')

def get_keys(s):
    keys = s._store.keys()

    if keys is None:
        return None

    return broker.Data.to_py(keys.get()) if keys.is_valid() else None

print("keys", get_keys(s))
```

> Is there a way to determine if the store is ready for use before actually referencing it?

If the query returns `None`, then it's currently in a disconnected/failure state and needs to be retried later.
