### ISSUE TITLE
Python Bindings: Malformed Zeek events cause segmentation fault

### ISSUE THREAD

**Issue by 0ortmann** [zeek/broker#85]
### Bug description:
When using the python bindings, malformed broker messages can lead to a segfault of the receiving python process.

**Zeek Version**: `v3.0.1`
**Broker Version**: `v1.2.4`

#### Minimal example:
1. Sender sends an invalid event
```py
import broker
ep = broker.Endpoint()
ep.peer("localhost", 9999)
ep.publish("topic", None)
```
2. Receiver parses messages
```py
import broker
ep = broker.Endpoint()
ep.listen('localhost', 9999)
sub = ep.make_subscriber('topic')
msg = sub.get()    # wait for sender (1)
parsed = broker.zeek.Event(msg)
parsed.args()      # <-- this segfaults
# parsed.name()    # <-- that would also segfault
```

I tested the following variations and all do lead to a segfault on the receiving side:
```
ep.publish("topic", None)
ep.publish("topic", "hi")
ep.publish("topic", 0)
ev = broker.zeek.Event(None)
ep.publish("topic", ev)
```

### Expected behavior:
Python receiver does not segfault.

#### Comparison -- Zeek behavior:

Interestingly, Zeek does not segfault when it receives malformed messages. Using the same python sender and the following receiver code, Zeek simply prints a warning. 

```sh
event zeek_init() {
    Broker::listen("localhost", 9999/tcp);
    Broker::subscribe("topic");
}
```

`warning: received invalid broker message: nil`

**Comment by jsiwek** [comment]
Thanks for the report.  This is addressed via #86 and should be able to backport to Zeek v3.0.2 and Broker v1.2.5.

The patch adds a `valid()` method you can call on `broker.zeek.Event` objects before trying to inspect its `name()` or `args()` or else those also now throw a `ValueError` if the received data could not be formed into a valid `Event` object.  Example:

```python
...
msg = sub.get()
parsed = broker.zeek.Event(msg[1])

print(f'  valid: {parsed.valid()}')

try:
    print(f'  args: {parsed.args()}')
    print(f'  name: {parsed.name()}')
except ValueError as e:
    print(f'  exception: {e}')
```

Also note the example originally provided generally won't parse out a valid `Event` because `get()` returns a `(topic, data)` tuple and only the `data` part relates to the `Event` parsing:

```python
msg = sub.get()
 # note: this is generally a mistake since get() return a (topic, data) tuple
parsed = broker.zeek.Event(msg)
```
